import type { GalleryImage } from '../types/content';
import { withBase } from '../utils/basePath';

export const media = {
  heroExterior: { src: withBase('/media/index-4.jpg'), alt: 'Exterior histórico de La Quinta del Ynfanzon' },
  logo: { src: withBase('/media/logo.jpg'), alt: 'Logotipo histórico de La Quinta del Ynfanzon' },
  portal: { src: withBase('/media/portal.jpg'), alt: 'Entrada principal y portal de la casona' },
  salon4: { src: withBase('/media/salon-4.jpg'), alt: 'Salon preparado para banquete' },
  fantasma: { src: withBase('/media/fantasma-copia.jpg'), alt: 'Retrato de Dona Ana de Solis' },
  felipe: { src: withBase('/media/d-felipe.jpg'), alt: 'Retrato de Don Felipe' },
  terrazaCopa: { src: withBase('/media/terrazacopa.jpg'), alt: 'Terraza principal para copas y tapas' },
  terrazaElena: { src: withBase('/media/terrazaelena.jpg'), alt: 'Mesas en terraza exterior' },
  terrazaFuera: { src: withBase('/media/terrazofuera.jpg'), alt: 'Vista abierta de la terraza' },
  piano: { src: withBase('/media/piano2.jpg'), alt: 'Salon comedor de carta' },
  piano2002: { src: withBase('/media/piano2002.jpg'), alt: 'Detalle del salon comedor' },
  chimenea: { src: withBase('/media/chimenefuego.jpg'), alt: 'Chimenea encendida en salon interior' },
  cristalera: { src: withBase('/media/cristalera.jpg'), alt: 'Salon grande con cristaleras' },
  salonNieve: { src: withBase('/media/salonieve.jpg'), alt: 'Salon grande en invierno' },
  comedorPiano: { src: withBase('/media/comedorpiano.jpg'), alt: 'Comedor de carta' },
  comunion: { src: withBase('/media/depiejacos.jpg'), alt: 'Celebracion de comunion en finca' },
  hinchable: { src: withBase('/media/inchable.jpg'), alt: 'Castillo hinchable infantil' },
  panoramica: { src: withBase('/media/panoramica.jpg'), alt: 'Panoramica de finca y jardines' },
  casanoche: { src: withBase('/media/casanoche.jpg'), alt: 'La Quinta iluminada de noche' },
  puertahotel: { src: withBase('/media/puertahotel.jpg'), alt: 'Entrada de la casa de aldea' },
  billar: { src: withBase('/media/billar.jpg'), alt: 'Salon billar del hotel' },
  lanora: { src: withBase('/media/lanora.jpg'), alt: 'Playa de La Nora' },
  estano: { src: withBase('/media/playaestano.jpg'), alt: 'Playa de Estano' },
  fincaGeneral: { src: withBase('/media/generalpalmera.jpg'), alt: 'Vista general de la finca' },
  canaveral: { src: withBase('/media/canaveral.jpg'), alt: 'Canaveral de bambu en jardines' },
  melandro: { src: withBase('/media/melandro.jpg'), alt: 'Melandro en los jardines' },
  columpio: { src: withBase('/media/3columpio.jpg'), alt: 'Zona de columpios infantil' },
  plazoleta1926: { src: withBase('/media/plazoletantig.jpg'), alt: 'Plazoleta historica circa 1926' },
  salon1926: { src: withBase('/media/salonold.jpg'), alt: 'Salon historico circa 1926' },
  frente1952: { src: withBase('/media/frente-copia.jpg'), alt: 'Frente de la casona circa 1952' },
  camino1952: { src: withBase('/media/caminifachada-copia.jpg'), alt: 'Camino de cerezos circa 1952' },
  plazoleta1962: { src: withBase('/media/plazoleta-copia.jpg'), alt: 'Plazoleta circa 1962' },
  fachada1962: { src: withBase('/media/fachada-copia.jpg'), alt: 'Fachada circa 1962' },
  plano: { src: withBase('/media/planoweb.jpg'), alt: 'Plano de accesos y aparcamiento' },
  entrada: { src: withBase('/media/entrada.jpg'), alt: 'Entrada principal a la finca' },
  planIcon: { src: withBase('/media/planin-copia2.gif'), alt: 'Icono historico de plano' },
  rampaDelantera: { src: withBase('/media/rampaterrazaterraza.jpg'), alt: 'Rampa delantera de accesibilidad' },
  rampaTrasera: { src: withBase('/media/rampatrasera.jpg'), alt: 'Rampa trasera de accesibilidad' },
  todoBar: { src: withBase('/media/todobar.jpg'), alt: 'Barra de cafeteria' },
  casaluz: { src: withBase('/media/casaluz.jpg'), alt: 'Casa iluminada por la noche' },
} as const;

export const galleryHighlights: GalleryImage[] = [
  {
    key: 'portal',
    alt: 'Entrada y portal de La Quinta',
    caption: 'Portal principal',
    source: { file: 'index.html', section: 'hero' },
  },
  {
    key: 'todoBar',
    alt: 'Barra de cafeteria',
    caption: 'Cafeteria',
    source: { file: 'terraza.html', section: 'cafeteria' },
  },
  {
    key: 'terrazaCopa',
    alt: 'Terraza para copas y tapas',
    caption: 'Terraza',
    source: { file: 'terraza_utf8.html', section: 'terraza' },
  },
  {
    key: 'casaluz',
    alt: 'Casona iluminada de noche',
    caption: 'La Quinta de noche',
    source: { file: 'nochevieja.html', section: 'imagen principal' },
  },
  {
    key: 'puertahotel',
    alt: 'Entrada de la casa de aldea',
    caption: 'Hotel rural',
    source: { file: 'hotel_utf8.html', section: 'entrada' },
  },
  {
    key: 'piano',
    alt: 'Salon comedor de carta',
    caption: 'Salon comedor',
    source: { file: 'salon.html', section: 'comedor' },
  },
  {
    key: 'cristalera',
    alt: 'Salon grande con cristaleras',
    caption: 'Salon de eventos',
    source: { file: 'salon.html', section: 'salon grande' },
  },
  {
    key: 'fincaGeneral',
    alt: 'Jardines y finca',
    caption: 'La finca',
    source: { file: 'finca.html', section: 'jardines' },
  },
  {
    key: 'plano',
    alt: 'Plano de accesos',
    caption: 'Accesos',
    source: { file: 'accesos.html', section: 'plano' },
  },
];
