import type { GalleryImage } from '../types/content';

export const media = {
  heroExterior: { src: '/media/index-4.jpg', alt: 'Exterior histórico de La Quinta del Ynfanzon' },
  logo: { src: '/media/logo.jpg', alt: 'Logotipo histórico de La Quinta del Ynfanzon' },
  portal: { src: '/media/portal.jpg', alt: 'Entrada principal y portal de la casona' },
  salon4: { src: '/media/salon-4.jpg', alt: 'Salon preparado para banquete' },
  fantasma: { src: '/media/fantasma-copia.jpg', alt: 'Retrato de Dona Ana de Solis' },
  felipe: { src: '/media/d-felipe.jpg', alt: 'Retrato de Don Felipe' },
  terrazaCopa: { src: '/media/terrazacopa.jpg', alt: 'Terraza principal para copas y tapas' },
  terrazaElena: { src: '/media/terrazaelena.jpg', alt: 'Mesas en terraza exterior' },
  terrazaFuera: { src: '/media/terrazofuera.jpg', alt: 'Vista abierta de la terraza' },
  piano: { src: '/media/piano2.jpg', alt: 'Salon comedor de carta' },
  piano2002: { src: '/media/piano2002.jpg', alt: 'Detalle del salon comedor' },
  chimenea: { src: '/media/chimenefuego.jpg', alt: 'Chimenea encendida en salon interior' },
  cristalera: { src: '/media/cristalera.jpg', alt: 'Salon grande con cristaleras' },
  salonNieve: { src: '/media/salonieve.jpg', alt: 'Salon grande en invierno' },
  comedorPiano: { src: '/media/comedorpiano.jpg', alt: 'Comedor de carta' },
  comunion: { src: '/media/depiejacos.jpg', alt: 'Celebracion de comunion en finca' },
  hinchable: { src: '/media/inchable.jpg', alt: 'Castillo hinchable infantil' },
  panoramica: { src: '/media/panoramica.jpg', alt: 'Panoramica de finca y jardines' },
  casanoche: { src: '/media/casanoche.jpg', alt: 'La Quinta iluminada de noche' },
  puertahotel: { src: '/media/puertahotel.jpg', alt: 'Entrada de la casa de aldea' },
  billar: { src: '/media/billar.jpg', alt: 'Salon billar del hotel' },
  lanora: { src: '/media/lanora.jpg', alt: 'Playa de La Nora' },
  estano: { src: '/media/playaestano.jpg', alt: 'Playa de Estano' },
  fincaGeneral: { src: '/media/generalpalmera.jpg', alt: 'Vista general de la finca' },
  canaveral: { src: '/media/canaveral.jpg', alt: 'Canaveral de bambu en jardines' },
  melandro: { src: '/media/melandro.jpg', alt: 'Melandro en los jardines' },
  columpio: { src: '/media/3columpio.jpg', alt: 'Zona de columpios infantil' },
  plazoleta1926: { src: '/media/plazoletantig.jpg', alt: 'Plazoleta historica circa 1926' },
  salon1926: { src: '/media/salonold.jpg', alt: 'Salon historico circa 1926' },
  frente1952: { src: '/media/frente-copia.jpg', alt: 'Frente de la casona circa 1952' },
  camino1952: { src: '/media/caminifachada-copia.jpg', alt: 'Camino de cerezos circa 1952' },
  plazoleta1962: { src: '/media/plazoleta-copia.jpg', alt: 'Plazoleta circa 1962' },
  fachada1962: { src: '/media/fachada-copia.jpg', alt: 'Fachada circa 1962' },
  plano: { src: '/media/planoweb.jpg', alt: 'Plano de accesos y aparcamiento' },
  entrada: { src: '/media/entrada.jpg', alt: 'Entrada principal a la finca' },
  planIcon: { src: '/media/planin-copia2.gif', alt: 'Icono historico de plano' },
  rampaDelantera: { src: '/media/rampaterrazaterraza.jpg', alt: 'Rampa delantera de accesibilidad' },
  rampaTrasera: { src: '/media/rampatrasera.jpg', alt: 'Rampa trasera de accesibilidad' },
  todoBar: { src: '/media/todobar.jpg', alt: 'Barra de cafeteria' },
  casaluz: { src: '/media/casaluz.jpg', alt: 'Casa iluminada por la noche' },
} as const;

export const galleryHighlights: GalleryImage[] = [
  {
    key: 'portal',
    alt: 'Entrada y portal de La Quinta',
    caption: 'Portal principal',
    source: { file: 'index.html', section: 'hero' },
  },
  {
    key: 'todoBar',
    alt: 'Barra de cafeteria',
    caption: 'Cafeteria',
    source: { file: 'terraza.html', section: 'cafeteria' },
  },
  {
    key: 'terrazaCopa',
    alt: 'Terraza para copas y tapas',
    caption: 'Terraza',
    source: { file: 'terraza_utf8.html', section: 'terraza' },
  },
  {
    key: 'casaluz',
    alt: 'Casona iluminada de noche',
    caption: 'La Quinta de noche',
    source: { file: 'nochevieja.html', section: 'imagen principal' },
  },
  {
    key: 'puertahotel',
    alt: 'Entrada de la casa de aldea',
    caption: 'Hotel rural',
    source: { file: 'hotel_utf8.html', section: 'entrada' },
  },
  {
    key: 'piano',
    alt: 'Salon comedor de carta',
    caption: 'Salon comedor',
    source: { file: 'salon.html', section: 'comedor' },
  },
  {
    key: 'cristalera',
    alt: 'Salon grande con cristaleras',
    caption: 'Salon de eventos',
    source: { file: 'salon.html', section: 'salon grande' },
  },
  {
    key: 'fincaGeneral',
    alt: 'Jardines y finca',
    caption: 'La finca',
    source: { file: 'finca.html', section: 'jardines' },
  },
  {
    key: 'plano',
    alt: 'Plano de accesos',
    caption: 'Accesos',
    source: { file: 'accesos.html', section: 'plano' },
  },
];
